name: Test Planets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install

      - name: Run All Tests
        run: |
          npm test tests/planets.test.js
          npm test tests/films.test.js
          # npm test tests/nonExistentRoute.test.js
          # npm test tests/people.test.js
          # npm test tests/singleFilm.test.js
          # npm test tests/singlePlanet.test.js
          # npm test tests/singleStarship.test.js
          # npm test tests/species.test.js
          # npm test tests/starships.test.js
          # npm test tests/vehicles.test.js
